config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  #
  ## Admin routes
  #
  namespace :admin do
    resources :companies
    resources :coupons do
      collection do
        get(
          'import-coupons',
          to: 'coupons#import_coupons',
          as: :import_coupons
        )
        post(
          'create-import-coupons',
          to: 'coupons#create_import_coupons',
          as: :create_import_coupons
        )
      end
    end
    resources :company_coupons, path: 'company-coupons'
    resources :employees, only: [:index, :show, :destroy]
    get "/" => "home#index", as: :dashboard
  end

  #
  ## Global Routes
  #
  resources :employees, only: [:new, :create] do
    collection do
      get   'verify_employee_email'
      get   'email_is_valide'
      patch 'check_otp'
    end
  end

  root to: 'employees#new'
end

app/models/employee.rb
class Employee < ApplicationRecord
  #
  ## Associations
  #
  belongs_to(
    :company
  )
  has_many(
    :employee_coupons,
    dependent: :destroy
  )
  has_one(
    :employee_otp,
    dependent: :destroy
  )

  #
  ## Validations
  #
  validates(
    :prefix,
    presence: true,
    length: {
      maximum: 4
    }
  )
  validates(
    :middle_name,
    presence: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :first_name,
    presence: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :last_name,
    presence: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :company_id,
    presence: true
  )
  validates(
    :email,
    format: {
      with: EMAIL_REGEX
    },
    presence: true
  )
  validates(
    :contact_number,
    numericality: true,
    presence: true,
    length: {
      maximum: 20
    }
  )

  #
  ## Callbacks
  #
  before_validation :assign_company, :validate_email

  #
  ## Assign Coupon to Employee
  #
  def assign_coupon
    date = DateTime.now
    success = nil
    unless self.disabled
      company_coupon =  CompanyCoupon.where(
                          "company_id = ? and start_date <= ? and end_date >= ?",
                          self.company_id,
                          date,
                          date
                        ).first

      if !company_coupon.blank? && company_coupon.used_coupon < company_coupon.number_of_coupon
        rule = CompanyCouponRule.find_by_company_coupon_id(company_coupon.id)
        unless rule.blank?
          employee_coupan_ids = EmployeeCoupon.all.pluck(:coupon_id)
          coupon = Coupon.where.not(id: employee_coupan_ids).first
          employee_coupons = self.employee_coupons.where(company_coupon_id: company_coupon.id).order(:created_at)
          create_coupon = false

          if coupon.blank?
            create_coupon = false
          elsif employee_coupons.blank?
            create_coupon = true
          elsif rule.allowed_coupon == -1 && rule.duration == -1
            create_coupon = true
          elsif rule.allowed_coupon == -1 && rule.duration != -1
            duration = Employee.get_day_duration(employee_coupons.first.created_at.to_date)
            create_coupon = ( duration < rule.duration )
          elsif rule.allowed_coupon != -1 && rule.duration == -1
            create_coupon = ( employee_coupons.count < rule.allowed_coupon )
          elsif rule.allowed_coupon != -1 && rule.duration != -1
            duration = Employee.get_day_duration(employee_coupons.first.created_at.to_date)
            create_coupon = ( employee_coupons.count < rule.allowed_coupon && duration < rule.duration )
          end

          if create_coupon
            self.employee_coupons.create(coupon_id: coupon.id, company_coupon_id: company_coupon.id)
            company_coupon.update_column(:used_coupon, company_coupon.used_coupon + 1)
            success = true
          else
            success = false
          end
        end
      end
    end
    success
  end

  #
  ## full name of employee
  #
  def name
    [prefix, first_name, middle_name, last_name].compact.join(' ')
  end

  private
  #
  ## Validate Email is Verified or not?
  #
  def validate_email
    if self.new_record?
      email_record = Email.find_by(email: self.email, verified: true)
      if email_record.blank?
        errors.add(:email, 'Email is not verified.')
      end
    end
  end

  #
  ## Assign company id
  #
  def assign_company
    if self.new_record?
      unless self.email.blank?
        domain = self.email.split('@')
        company_domain = Company.find_by(domain: domain[1])
        unless company_domain.blank?
          self.company_id = company_domain.id
        else
          errors.add(:email, "Please enter valid email.")
        end
      end
    end
  end

  #
  ## Find Duration between two date
  #
  def self.get_day_duration(start_date, end_date = Date.today)
    unless start_date.blank? && end_date.blank?
      (start_date - end_date).to_i.abs
    end
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::AdminController

  #
  ## Before action callbacks
  #
  before_action(
    :set_employee,
    only: [
      :show,
      :edit,
      :update,
      :destroy
    ]
  )

  #
  ## For employee
  #
  def index
    @per_page   = (params[:per_page].blank? ? PER_PAGE : params[:per_page])
    @employees  = Employee.all.page(params[:page]).per(@per_page)
  end

  #
  ## show method employee
  #
  def show
  end

  #
  ## new method employee
  #
  def new
    @employee = Employee.new
  end

  #
  ## edit method employee
  #
  def edit
  end

  #
  ## create method employee
  #
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html {
          flash[:success] = 'employee was successfully created.'
          redirect_to admin_employee_path(@employee)
        }
        format.json {
          render(
            :show,
            status: :created,
            location: @employee
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :new
        }
        format.json {
          render(
            json: @employee.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## update method employee
  #
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html {
          flash[:success] = 'employee was successfully updated.'
          redirect_to admin_employee_path(@employee)
        }
        format.json {
          render(
            :show,
            status: :ok,
            location: @employee
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :edit
        }
        format.json {
          render(
            json: @employee.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## destroy method employee
  #
  def destroy
    data = @employee.disabled == true ? false : true
    @employee.update(disabled: data)
    respond_to do |format|
      format.html {
        flash[:delete] = 'employee was successfully destroyed.'
        redirect_to admin_employees_path
      }
      format.json { head :no_content }
    end
  end


  private
  #
  ## set employee id before show, edit, update and destroy methods
  #
  def set_employee
    @employee = Employee.find_by_id(params[:id])
    redirect_to admin_employees_path if @employee.blank?
  end

  #
  ## employee params
  #
  def employee_params
    params.require(:employee).permit(
      :prefix,
      :first_name,
      :middle_name,
      :last_name,
      :email,
      :contact_number,
      :address
    )
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  layout 'employee'

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.find_or_initialize_by(email: employee_params[:email])
    @employee.assign_attributes(employee_params)
    respond_to do |format|
      if @employee.save
        data = @employee.assign_coupon
        if data
          message = 'Coupon assigned successfully.'
        elsif data == false
          message = 'Coupon already assigned please try after some time.'
        else
          message = 'Employee was successfully created.'
        end
        format.html {
          flash[:success] = message
          redirect_to root_path
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :new
        }
        format.json {
          render(
            json: @employee.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  def verify_employee_email
    unless params[:email].blank?
      @email = params[:email]
      email = Email.find_or_initialize_by(
                email: @email,
                verified: false
              )
      otp = rand(0..9999).to_s.rjust(4,'0')
      email.otp = otp
      email.send_date = Time.now
      email.save
    end
    render layout: false
  end

  def email_is_valide
    employee_email = params[:email]
    unless employee_email.blank?
      email = Email.find_by(email: employee_email, verified: true)
      data = false
      if email.blank?
        domain = employee_email.split('@')
        company_domain = Company.find_by(domain: domain[1])
        if company_domain.blank?
          data = false
        else
          data = true
        end
      else
        data = 'available'
      end
    end
    render json: { data: data }
  end

  def check_otp
    status = 404
    unless params[:email].blank? && params[:otp]
      email = Email.find_by(
                email: params[:email],
                otp: params[:otp],
                verified: false
              )
      unless email.blank?
        email.update(verified: true)
        status = 200
      end
    end
    render json: {
      status: status
    }
  end

  private
  #
  ## set employee id before show, edit, update and destroy methods
  #
  def set_employee
    @employee = Employee.find_by_id(params[:id])
    redirect_to employees_path if @employee.blank?
  end

  #
  ## employee params
  #
  def employee_params
    params.require(:employee).permit(
      :prefix,
      :first_name,
      :middle_name,
      :last_name,
      :email,
      :contact_number,
      :address
    )
  end

end

app/views/employees/_form.html.haml
= form_for(employee, html: { class: "form-horizontal form-label-left"}) do |f|
  %h4 Employee Details
  - flash.each do |key, value|
    %div{class: "alert alert-#{key}"}= value

  %div{class: "form-group #{has_error(employee.errors, :prefix)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Prefix
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.select :prefix, options_for_select(PREFIX, employee.prefix), {prompt: 'Prefix'}, required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(employee.errors, :prefix)
  %div{class: "form-group #{has_error(employee.errors, :first_name)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      First Name
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :first_name, placeholder: 'First Name', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(employee.errors, :first_name)
  %div{class: "form-group #{has_error(employee.errors, :middle_name)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Middle Name
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :middle_name, placeholder: 'Middle Name', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(employee.errors, :middle_name)
  %div{class: "form-group #{has_error(employee.errors, :last_name)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Last Name
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :last_name, placeholder: 'Last Name', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(employee.errors, :last_name)
  %div{class: "form-group #{has_error(employee.errors, :email)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Email
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.email_field :email, placeholder: 'Email', class: 'form-control col-md-7 col-xs-12'
      .verify-true.col-md-3
        = link_to '#', title: 'Show', data: {toggle: 'modal', target: '.verify-otp', 'verify-url': verify_employee_email_employees_path}, id: "verify-button", class: 'btn btn-info btn-xs' do
          Verify
      .verify-available.col-md-7.green
        %h5 You'r email is already verified please continue
      .email-verify.col-md-7.green
        %h5 You'r email is successfully verified
      .email-invalid.col-md-7.red
        %h5 please enter valide email.
    = print_error(employee.errors, :email)
  %div{class: "form-group #{has_error(employee.errors, :contact_number)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Contact Number
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :contact_number, placeholder: 'Contact Number', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(employee.errors, :contact_number)
  %div{class: "form-group #{has_error(employee.errors, :address)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Address
    .col-md-6.col-sm-6.col-xs-12
      = f.text_area :address, placeholder: 'Address' , class: 'form-control col-md-7 col-xs-12', cols: 20, rows: 10
    = print_error(employee.errors, :address)
  %span.clearfix
  .ln_solid

  .form-group
    .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
      = link_to 'Cancel', root_path, class: 'btn btn-primary'
      = f.submit 'Save', class: 'btn btn-success'

#verify-otp.modal.fade.verify-otp{"aria-hidden": "true", "aria-labelledby": "mySmallModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content

:javascript
  $(document).ready(function() {
    $('#verify-button').addClass('disabled')
    $('.verify-true').hide()
    $('.email-verify').hide()
    $('.verify-available').hide()
    $('.email-invalid').hide()
    $('#employee_email').focusout(function(){
      email = $(this).val()
      validateEmail(email)
    })

    function validateEmail(employee_email) {
      var email = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      verify = email.test(employee_email);
      if (verify == true) {
        var request = $.ajax({
          url: '/employees/email_is_valide',
          type: 'get',
          data: { email: employee_email },
          dataType: 'JSON'
        });
        request.done(function(data){
          if (data['data'] == true) {
            $('.verify-true').show()
            $('.email-verify').hide()
            $('.verify-available').hide()
            $('#verify-button').addClass('active')
            $('#verify-button').removeClass('disabled')
            $('.email-invalid').hide()
          } else if (data['data'] == 'available') {
            $('.verify-true').hide()
            $('.email-verify').hide()
            $('.verify-available').show()
            $('#verify-button').addClass('disabled')
            $('#verify-button').removeClass('active')
            $('.email-invalid').hide()
          } else if (data['data'] == false) {
            $('.email-invalid').hide()
            $('.verify-true').hide()
            $('.email-verify').hide()
            $('.verify-available').hide()
            $('#verify-button').addClass('disabled')
            $('#verify-button').removeClass('active')
          }
        });
      } else {
        $('.email-invalid').show()
        $('.verify-true').hide()
        $('.email-verify').hide()
        $('.verify-available').hide()
        $('#verify-button').addClass('disabled')
        $('#verify-button').removeClass('active')
      }
      
    }

    $('.verify-otp').on('show.bs.modal', function(e) {
      var path = $(e.relatedTarget).data('verify-url');
      email = $('#employee_email').val()
      url = path+'?email='+email
      if (email){
        $(".verify-otp .modal-content").load(url);
      }
    });

  })

app/views/employees/new.html.haml
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Employee form
        .clearfix
      .x_content
        = render 'form', employee: @employee

app/views/employees/verify_employee_email.html.haml
.modal-header
  %h4.modal-title
    Verify OTP
  %h4.red
    * OTP sent on your given email.
.modal-body
  .row
    .col-lg-3.text-bold Email :
    .col-lg-9= @email
    .col-lg-3.text-bold OTP :
    .col-lg-9
      %input#email-otp.form-control{name: "email[otp]", placeholder: "Enter OTP", required: "required", type: "number", value: ""}
    #otp-error.red
      Plese enter valid OTP.
  .row
    .modal-footer
      %button#otp-form.btn.btn-primary.col-md-offset-5{type: "button"} Ok

:javascript
  $(document).ready(function() {
    $('#otp-error').hide()
    $('#otp-form').click(function() {
      var valuesToSubmit = $(this).serialize();
      otp = $('#email-otp').val()
      email = '#{@email}'
      url = '/employees/check_otp'

      if (otp) {
        request = $.ajax({
            type: "PATCH",
            url: url,
            data: {email: email, otp: otp},
            dataType: "JSON"
        });

        request.done(function(data){
          if (data['status'] == 200) {
            $('#verify-otp').modal('hide');
            $('.verify-true').hide()
            $('.email-verify').show()
            $('.verify-available').hide()
            $('#verify-button').addClass('disabled')
            $('#verify-button').removeClass('active')
          } else {
            $('#otp-error').show()
          }
        });
      }
    });
  });