config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  #
  ## Admin routes
  #
  namespace :admin do
    resources :companies
    resources :coupons do
      collection do
        get(
          'import-coupons',
          to: 'coupons#import_coupons',
          as: :import_coupons
        )
        post(
          'create-import-coupons',
          to: 'coupons#create_import_coupons',
          as: :create_import_coupons
        )
      end
    end
    resources :company_coupons, path: 'company-coupons'
    resources :employees, only: [:index, :show, :destroy]
    get "/" => "home#index", as: :dashboard
  end

  #
  ## Global Routes
  #
  resources :employees, only: [:new, :create] do
    collection do
      get   'verify_employee_email'
      get   'email_is_valide'
      patch 'check_otp'
    end
  end

  root to: 'employees#new'
end

app/models/company.rb
class Company < ApplicationRecord
  #
  ## Associations
  #
  has_many(
    :company_coupons,
    dependent: :destroy
  )
  has_many(
    :employees,
    dependent: :destroy
  )
  has_many(
    :company_coupon_rules,
    dependent: :destroy
  )

  #
  ## Validations
  #
  validates(
    :name,
    presence: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :email,
    format: {
      with: EMAIL_REGEX
    },
    presence: true,
    uniqueness: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :contact_number,
    presence: true,
    length: {
      maximum: 20
    }
  )
  validates(
    :domain,
    presence: true,
    uniqueness: true,
    length: {
      maximum: 50
    }
  )
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminController

  #
  ## Before action callbacks
  #
  before_action(
    :set_company,
    only: [
      :show,
      :edit,
      :update,
      :destroy
    ]
  )

  #
  ## For Company
  #
  def index
    @companies  = Company.all.page(@page).per(@per_page)
  end

  #
  ## show method Company
  #
  def show
  end

  #
  ## new method Company
  #
  def new
    @company = Company.new
  end

  #
  ## edit method Company
  #
  def edit
  end

  #
  ## create method Company
  #
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html {
          flash[:success] = 'Company was successfully created.'
          redirect_to [:admin, @company]
        }
        format.json {
          render(
            :show,
            status: :created,
            location: [:admin, @company]
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :new
        }
        format.json {
          render(
            json: @company.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## update method Company
  #
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html {
          flash[:success] = 'Company was successfully updated.'
          redirect_to [:admin, @company]
        }
        format.json {
          render(
            :show,
            status: :ok,
            location: [:admin, @company]
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :edit
        }
        format.json {
          render(
            json: @company.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## destroy method Company
  #
  def destroy
    @company.destroy
    respond_to do |format|
      format.html {
        flash[:delete] = 'Company was successfully destroyed.'
        redirect_to admin_companies_path
      }
      format.json { head :no_content }
    end
  end


  private
  #
  ## set Company id before show, edit, update and destroy methods
  #
  def set_company
    @company = Company.find_by_id(params[:id])
    redirect_to admin_companies_path if @company.blank?
  end

  #
  ## Company params
  #
  def company_params
    params.require(:company).permit(
      :name,
      :address,
      :email,
      :contact_number,
      :domain
    )
  end
end

app/views/admin/companies/_form.html.haml
= form_for([:admin, company] , html: { class: "form-horizontal form-label-left"}) do |f|
  %h4 Company Details
  %div{class: "form-group #{has_error(company.errors, :name)}"}
    .control-label.col-md-3.col-sm-3.col-xs-12
      Name
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :name, placeholder: 'Name', required: true, class: 'form-control col-md-7 col-xs-12'
    =print_error(company.errors, :name)

  %div{class: "form-group #{has_error(company.errors, :email)}"}
    .control-label.col-md-3.col-sm-3.col-xs-12
      Email
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.email_field :email, placeholder: 'Email', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(company.errors, :email)

  %div{class: "form-group #{has_error(company.errors, :contact_number)}"}
    .control-label.col-md-3.col-sm-3.col-xs-12
      Contact Number
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :contact_number, placeholder: 'Contact Number', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(company.errors, :contact_number)

  %div{class: "form-group #{has_error(company.errors, :domain)}"}
    .control-label.col-md-3.col-sm-3.col-xs-12
      Domain
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :domain, placeholder: 'Domain', class: 'form-control col-md-7 col-xs-12', required: true
    = print_error(company.errors, :domain)

  %div{class: "form-group #{has_error(company.errors, :address)}"}
    .control-label.col-md-3.col-sm-3.col-xs-12
      Address
    .col-md-6.col-sm-6.col-xs-12
      = f.text_area :address, placeholder: 'Address', class: 'form-control col-md-7 col-xs-12', cols: 20, rows: 10
    = print_error(company.errors, :address)

  %span.clearfix

  .ln_solid

  .form-group
    .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
      = link_to "Cancel", admin_companies_path, class: "btn btn-primary"
      = f.submit "Save", class: "btn btn-success"

app/views/admin/companies/edit.html.haml
.page-title
  .title_left
    %h3 Company
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Edit Company
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{:href => admin_companies_path} Companies
        .clearfix
      .x_content
        = render 'form', company: @company

app/views/admin/companies/index.html.haml
.page-title
  .title_left
    %h3 Companies
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Companies
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{href: new_admin_company_path} New Company
        .clearfix
      .x_content
        .row
          .col-sm-12.col-xs-12.col-md-12
            %table.table.table-striped.projects
              %thead
                %tr
                  %th #
                  %th Name
                  %th Email
                  %th Contact Number
                  %th Domain
              %tbody
                - @companies.each do |company|
                  %tr
                    %td= company.id
                    %td= company.name
                    %td= company.email
                    %td= company.contact_number
                    %td= company.domain
                    %td.text-right
                      .btn-group
                        = link_to 'Coupons', admin_company_coupons_path(company_id: company), class: 'btn btn-xs btn-info'
                        = link_to 'Show', admin_company_path(company), class: 'btn btn-xs btn-primary', type:'button'
                        = link_to 'Edit', edit_admin_company_path(company), class: 'btn btn-xs btn-primary', type:'button'
                        = link_to 'Destroy', admin_company_path(company), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger', type:'button'

app/views/admin/companies/new.html.haml
.page-title
  .title_left
    %h3 Company
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 New Company
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{:href => admin_companies_path} Companies
        .clearfix
      .x_content
        = render 'form', company: @company

app/views/admin/companies/show.html.haml
.page-title
  .title_left
    %h3 Companies
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2
          Company -
          %small
            = @company.name
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{:href => admin_companies_path} Companies
          = link_to 'Edit', edit_admin_company_path(@company), class: "btn btn-sm btn-primary"
        .clearfix
      .x_content
        .row
          .col-sm-6
            %h4 Company Details
            %dl.dl-horizontal
              %dt Name:
              %dd= @company.name
              %dt Email:
              %dd= @company.email
              %dt Contact Number:
              %dd= @company.contact_number
              %dt Domain:
              %dd= @company.domain
              %dt Address:
              %dd= @company.address