config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  #
  ## Admin routes
  #
  namespace :admin do
    resources :companies
    resources :coupons do
      collection do
        get(
          'import-coupons',
          to: 'coupons#import_coupons',
          as: :import_coupons
        )
        post(
          'create-import-coupons',
          to: 'coupons#create_import_coupons',
          as: :create_import_coupons
        )
      end
    end
    resources :company_coupons, path: 'company-coupons'
    resources :employees, only: [:index, :show, :destroy]
    get "/" => "home#index", as: :dashboard
  end

  #
  ## Global Routes
  #
  resources :employees, only: [:new, :create] do
    collection do
      get   'verify_employee_email'
      get   'email_is_valide'
      patch 'check_otp'
    end
  end

  root to: 'employees#new'
end

app/views/layouts/partials/_footer.html.haml
%footer
  .pull-right
    Coupon Management
  .clearfix

app/views/layouts/partials/_sidebar.html.haml
.col-md-3.left_col.menu_fixed
  .left_col.scroll-view
    .navbar.nav_title{style: "border: 0;"}
      %a.site_title{href: "javascript:;"}
        %i.fa.fa-paw
        %span CPM
    .clearfix
    #sidebar-menu.main_menu_side.hidden-print.main_menu
      .menu_section.active
        %h3  
        %ul.nav.side-menu
          %li{class: "#{'current-page' if controller_name == 'home'}"}
            %a{class: "#{'active' if controller_name == 'home'}", href: admin_dashboard_path}
              %i.fa.fa-home
              Home
          %li{class: "#{'current-page' if controller_name == 'companies'}"}
            %a{class: "#{'active' if controller_name == 'companies'}", href: admin_companies_path}
              %i.fa.fa-home
              Companies
          %li{class: "#{'current-page' if controller_name == 'employees'}"}
            %a{class: "#{'active' if controller_name == 'employees'}", href: admin_employees_path}
              %i.fa.fa-user
              Employees
          %li{class: "#{'current-page' if controller_name == 'coupons'}"}
            %a{class: "#{'active' if controller_name == 'coupons'}", href: admin_coupons_path}
              %i.fa.fa-user
              Coupons
          %li{class: "#{'current-page' if controller_name == 'company_coupons'}"}
            %a{class: "#{'active' if controller_name == 'company_coupons'}", href: admin_company_coupons_path}
              %i.fa.fa-user
              Company Coupons

app/views/layouts/partials/_topnavbar.html.haml
.top_nav
  .nav_menu
    %nav
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{"data-method": "delete", href: destroy_admin_session_path}
            %i.fa.fa-sign-out
            Log Out