config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  #
  ## Admin routes
  #
  namespace :admin do
    resources :companies
    resources :coupons do
      collection do
        get(
          'import-coupons',
          to: 'coupons#import_coupons',
          as: :import_coupons
        )
        post(
          'create-import-coupons',
          to: 'coupons#create_import_coupons',
          as: :create_import_coupons
        )
      end
    end
    resources :company_coupons, path: 'company-coupons'
    resources :employees, only: [:index, :show, :destroy]
    get "/" => "home#index", as: :dashboard
  end

  #
  ## Global Routes
  #
  resources :employees, only: [:new, :create] do
    collection do
      get   'verify_employee_email'
      get   'email_is_valide'
      patch 'check_otp'
    end
  end

  root to: 'employees#new'
end

app/models/coupon.rb
class Coupon < ApplicationRecord

  #
  ## Associations
  #
  has_many(
    :company_coupons,
    dependent: :destroy
  )
  has_many(
    :employee_coupons,
    dependent: :destroy
  )
  has_many(
    :company_coupon_rules,
    dependent: :destroy
  )

  #
  ## Validations
  #
  validates(
    :code,
    presence: true,
    uniqueness: true,
    length: {
      maximum: 50
    }
  )
  validates(
    :expiry_date,
    presence: true
  )
  validates(
    :vendor,
    presence: true,
    length: {
      maximum: 100
    }
  )
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::AdminController

  #
  ## Before action callbacks
  #
  before_action(
    :set_coupon,
    only: [
      :show,
      :edit,
      :update,
      :destroy
    ]
  )

  #
  ## For Coupon
  #
  def index
    @per_page = (params[:per_page].blank? ? PER_PAGE : params[:per_page])
    @coupons  = Coupon.all.page(params[:page]).per(@per_page)
  end

  #
  ## show method Coupon
  #
  def show
  end

  #
  ## new method Coupon
  #
  def new
    @coupon = Coupon.new
  end

  #
  ## edit method Coupon
  #
  def edit
  end

  #
  ## create method Coupon
  #
  def create
    @coupon = Coupon.new(coupon_params)
    respond_to do |format|
      if @coupon.save
        format.html {
          flash[:success] = 'Coupon was successfully created.'
          redirect_to admin_coupon_path(@coupon)
        }
        format.json {
          render(
            :show,
            status: :created,
            location: @coupon
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :new
        }
        format.json {
          render(
            json: @coupon.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## update method Coupon
  #
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html {
          flash[:success] = 'Coupon was successfully updated.'
          redirect_to admin_coupon_path(@coupon)
        }
        format.json {
          render(
            :show,
            status: :ok,
            location: @coupon
          )
        }
      else
        format.html {
          flash[:alert] = 'Please fill correct data.'
          render :edit
        }
        format.json {
          render(
            json: @coupon.errors,
            status: :unprocessable_entity
          )
        }
      end
    end
  end

  #
  ## destroy method Coupon
  #
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html {
        flash[:delete] = 'Coupon was successfully destroyed.'
        redirect_to admin_coupons_path
      }
      format.json { head :no_content }
    end
  end

  def import_coupons
  end

  #
  ## create import Coupons record
  #
  def create_import_coupons
    file = params[:file]
    unless file.blank?
      spreadsheet = open_file(file)
      header      = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        if !row["Code"].blank? && !row["Expiry Date"].blank?
          coupon = Coupon.new(
            code: row["Code"],
            expiry_date: row["Expiry Date"],
            description: row["Description"],
            vendor: row["Vendor"]
          )
          coupon.save
        end
      end
      flash[:success] = 'Import coupon was successfully created.'
      redirect_to admin_coupons_path
    else
      flash[:alert] = 'Import coupon File not found.'
      redirect_to admin_coupons_path
    end
  end

  #
  ## open file
  #
  def open_file(file)
    begin
      case File.extname(file.original_filename)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    rescue Exception => e
      logger.info e
    end
  end

  private
  #
  ## set Coupon id before show, edit, update and destroy methods
  #
  def set_coupon
    @coupon = Coupon.find_by_id(params[:id])
    redirect_to admin_coupons_path if @coupon.blank?
  end

  #
  ## Coupon params
  #
  def coupon_params
    params.require(:coupon).permit(
      :code,
      :expiry_date,
      :description,
      :vendor
    )
  end
end

app/views/admin/coupons/_form.html.haml
= form_for([:admin, coupon] , html: { class: "form-horizontal form-label-left"}) do |f|
  %h4 Coupon Details
  %div{class: "form-group #{has_error(coupon.errors, :code)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Code
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :code, placeholder: 'Code', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(coupon.errors, :code)
  %div{class: "form-group #{has_error(coupon.errors, :expiry_date)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Expiry Date
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :expiry_date, placeholder: 'Expiry Date', required: true, class: 'form-control col-md-7 col-xs-12 datetimepicker', id: 'expiry_date'
    = print_error(coupon.errors, :expiry_date)
  %div{class: "form-group #{has_error(coupon.errors, :vendor)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Vendor
      %span.required *
    .col-md-6.col-sm-6.col-xs-12
      = f.text_field :vendor, placeholder: 'Vendor', required: true, class: 'form-control col-md-7 col-xs-12'
    = print_error(coupon.errors, :vendor)
  %div{class: "form-group #{has_error(coupon.errors, :description)}"}
    %label.control-label.col-md-3.col-sm-3.col-xs-12
      Description
    .col-md-6.col-sm-6.col-xs-12
      = f.text_area :description, placeholder: 'Description' , class: 'form-control col-md-7 col-xs-12', cols: 20, rows: 10
    = print_error(coupon.errors, :description)
  %span.clearfix
  .ln_solid

  .form-group
    .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
      = link_to "Cancel", admin_coupons_path, class: "btn btn-primary"
      = f.submit "Save", class: "btn btn-success"

:javascript
  $("#expiry_date").datetimepicker({
    format: 'YYYY-MM-DD HH:mm',
    icons: {
      time: "fa fa-clock-o",
      date: "fa fa-calendar",
      up: "fa fa-arrow-up",
      down: "fa fa-arrow-down",
      previous: "fa fa-arrow-left",
      next: "fa fa-arrow-right"
    }
  });

app/views/admin/coupons/edit.html.haml
.page-title
  .title_left
    %h3 Coupon
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Edit Coupon
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{href: admin_coupons_path} Coupons
        .clearfix
      .x_content
        = render 'form', coupon: @coupon

app/views/admin/coupons/import_coupons.html.haml
.page-title
  .title_left
    %h3 Coupon
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Import Coupons
        .nav.navbar-right
          = link_to 'Coupons', admin_coupons_path, class: "btn btn-sm btn-primary"
        .clearfix
      .x_content
        = form_tag(create_import_coupons_admin_coupons_path, multipart: true, html: { class: 'form-horizontal form-label-left'}) do |f|
          %h4 Coupon Details
          %label.control-label.col-md-3.col-sm-3.col-xs-12
            File
            %span.required *
          .col-md-6.col-sm-6.col-xs-12
            = file_field_tag :file, placeholder: 'File', required: true, class: 'form-control col-md-7 col-xs-12'
        %span.clearfix
        .ln_solid
        .form-group
          .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
            = link_to 'Cancel', admin_coupons_path, class: "btn btn-primary"
            %button.btn.btn-success{"data-disable-with": "Saving...", type: "submit"} Save

app/views/admin/coupons/index.html.haml
.page-title
  .title_left
    %h3 Coupons
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 Coupons
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{href: import_coupons_admin_coupons_path} Import Coupons
          %a.btn.btn-sm.btn-primary{href: new_admin_coupon_path} New Coupon
        .clearfix
      .x_content
        .row
          .col-sm-12.col-xs-12.col-md-12
            %table.table.table-striped.projects
              %thead
                %tr
                  %th #
                  %th Code
                  %th Expiry Date
                  %th Vendor
              %tbody
                - @coupons.each do |coupon|
                  %tr
                    %td= coupon.id
                    %td= coupon.code
                    %td= coupon.expiry_date
                    %td= coupon.vendor
                    %td.text-right
                      .btn-group
                        = link_to 'Show', admin_coupon_path(coupon), class: 'btn btn-xs btn-primary', type:'button'
                        = link_to 'Edit', edit_admin_coupon_path(coupon), class: 'btn btn-xs btn-primary', type:'button'
                        = link_to 'Destroy', admin_coupon_path(coupon), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger', type:'button'

app/views/admin/coupons/new.html.haml
.page-title
  .title_left
    %h3 Coupon
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2 New Coupon
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{href: admin_coupons_path} Coupons
        .clearfix
      .x_content
        = render 'form', coupon: @coupon

app/views/admin/coupons/show.html.haml
.page-title
  .title_left
    %h3 Coupons
.clearfix
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2
          Coupon -
          %small
            = @coupon.code
        .nav.navbar-right
          %a.btn.btn-sm.btn-primary{href: admin_coupons_path} Coupons
          = link_to 'Edit', edit_admin_coupon_path(@coupon), class: "btn btn-sm btn-primary"
        .clearfix
      .x_content
        .row
          .col-sm-6
            %h4 Coupon Details
            %dl.dl-horizontal
              %dt Code:
              %dd= @coupon.code
              %dt Expiry Date:
              %dd= @coupon.expiry_date
              %dt Vendor:
              %dd= @coupon.vendor
              %dt Description:
              %dd= @coupon.description